"""add fallback_advertiser_id to advertisers

Revision ID: c2149f0a58d0
Revises: 
Create Date: 2025-03-17 14:14:43.587166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2149f0a58d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_id', table_name='services')
    op.drop_table('services')
    op.add_column('advertisers', sa.Column('fallback_advertiser_id', sa.Integer(), nullable=True))
    op.alter_column('advertisers', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('advertisers', 'company_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('advertisers', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('advertisers', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('advertisers', 'capping',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_advertisers_email', table_name='advertisers')
    op.drop_index('ix_advertisers_name', table_name='advertisers')
    op.create_foreign_key(None, 'advertisers', 'advertisers', ['fallback_advertiser_id'], ['id'])
    op.drop_column('advertisers', 'block_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisers', sa.Column('block_rule', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'advertisers', type_='foreignkey')
    op.create_index('ix_advertisers_name', 'advertisers', ['name'], unique=False)
    op.create_index('ix_advertisers_email', 'advertisers', ['email'], unique=True)
    op.alter_column('advertisers', 'capping',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('advertisers', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('advertisers', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('advertisers', 'company_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('advertisers', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('advertisers', 'fallback_advertiser_id')
    op.create_table('services',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('msisdn', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('operator_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('vendor_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('service_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('short_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('piincode', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('advertiser_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name='services_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_services_id', 'services', ['id'], unique=False)
    # ### end Alembic commands ###
